---
title: "covid19"
authors: Diane Kim, Arielle Hutchinson, Priya Parkash
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(tidyverse)
library("dplyr")
library(stringr)
library(RCurl)
library(betareg)
```
```{r load-data}
date_of_study = "04-20-2020"

covid_hist = read.csv(text=getURL("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-30-2020.csv"))
covid_us_hist = subset(covid_hist, Country_Region == "US" & is.na(FIPS)==F)

covid = read.csv(text=getURL(paste0("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/",date_of_study,".csv")))
covid_us = subset(covid,Country_Region == "US" & is.na(FIPS)!=T)
covid_us = rbind(covid_us,subset(covid_us_hist, (!(FIPS %in% covid_us$FIPS))  & Confirmed == 0 & Deaths == 0 & is.na(FIPS)==F))

county_pm = read.csv(text=getURL("https://raw.githubusercontent.com/wxwx1993/PM_COVID/master/Data/county_pm25.csv"))

pm_ave <- read_csv("county_pm_ave.csv")

dem <- read_csv("co-est2019-alldata.csv")

census <- read_csv("census_county_interpolated.csv")

census_ave <- read_csv("census_ave.csv")


```

```{r clean-up-data}
county_pm %>%
  count(fips)

covid_us <- covid_us %>%
  mutate(fips = FIPS)

pm_mean = county_pm %>% 
  group_by(fips) %>% 
  summarise(pm25 = mean(pm25))
  
```

```{r deaths-proportion}
covid_us <- covid_us %>%
  group_by(fips) %>%
  mutate(mortality = (1+Deaths)/Confirmed) %>%
  filter(mortality<1 & !is.na(mortality))
```

```{r}
fullset <- inner_join(covid_us, pm_mean, by = "fips")
ggplot(data = fullset, mapping = aes(x = mortality))+
  geom_histogram()

full <- inner_join(covid_us, census_ave, by = "fips")
full <- full %>%
  mutate(poverty = 100*poverty, medianhouseholdincome = medianhouseholdincome/1000, medianhousevalue = medianhousevalue/1000, pct_blk = pct_blk*100, pct_asian = pct_asian*100, pct_native = pct_native*100, hispanic = hispanic*100, pct_white = pct_white*100, education = education*100)
```

```{r eda}
ggplot(data = full, mapping = aes(x = mortality))+
  geom_histogram()+
  labs(title = "Distribution of Mortality Rate", x = "Mortality", y = "Frequency")

ggplot(data = full, mapping = aes(x = poverty))+
  geom_histogram()+
  labs(title = "Distribution of Poverty Rate", x = "Poverty Rate (in percentages)", y = "Frequency")

ggplot(data = full, mapping = aes(x = poverty, y = mortality))+
  geom_point()

ggplot(data = full, mapping = aes(x = pct_asian, y = mortality))+
  geom_point()
```


```{r betareg}
mod <- betareg(mortality ~ poverty + medianhouseholdincome + medianhousevalue + hispanic + pct_asian + pct_white + pct_native + education + popdensity + poverty*pct_blk +poverty*pct_native, data = full)
tidy(mod) %>%
  kable(format = "markdown", digits = 6)
```

